{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2009-2659", "ASSIGNER": "cve@mitre.org"}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-22"}]}]}, "references": {"reference_data": [{"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134", "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134", "refsource": "", "tags": []}, {"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134", "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134", "refsource": "", "tags": []}, {"url": "http://code.djangoproject.com/changeset/11353", "name": "http://code.djangoproject.com/changeset/11353", "refsource": "", "tags": []}, {"url": "http://code.djangoproject.com/changeset/11353", "name": "http://code.djangoproject.com/changeset/11353", "refsource": "", "tags": []}, {"url": "http://secunia.com/advisories/36137", "name": "36137", "refsource": "", "tags": []}, {"url": "http://secunia.com/advisories/36137", "name": "36137", "refsource": "", "tags": []}, {"url": "http://secunia.com/advisories/36153", "name": "36153", "refsource": "", "tags": []}, {"url": "http://secunia.com/advisories/36153", "name": "36153", "refsource": "", "tags": []}, {"url": "http://www.djangoproject.com/weblog/2009/jul/28/security/", "name": "http://www.djangoproject.com/weblog/2009/jul/28/security/", "refsource": "", "tags": ["Patch", "Vendor Advisory"]}, {"url": "http://www.djangoproject.com/weblog/2009/jul/28/security/", "name": "http://www.djangoproject.com/weblog/2009/jul/28/security/", "refsource": "", "tags": ["Patch", "Vendor Advisory"]}, {"url": "http://www.openwall.com/lists/oss-security/2009/07/29/2", "name": "[oss-security] 20090729 CVE Request (django)", "refsource": "", "tags": []}, {"url": "http://www.openwall.com/lists/oss-security/2009/07/29/2", "name": "[oss-security] 20090729 CVE Request (django)", "refsource": "", "tags": []}, {"url": "http://www.securityfocus.com/bid/35859", "name": "35859", "refsource": "", "tags": []}, {"url": "http://www.securityfocus.com/bid/35859", "name": "35859", "refsource": "", "tags": []}, {"url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00055.html", "name": "FEDORA-2009-8169", "refsource": "", "tags": []}, {"url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00055.html", "name": "FEDORA-2009-8169", "refsource": "", "tags": []}, {"url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00069.html", "name": "FEDORA-2009-8177", "refsource": "", "tags": []}, {"url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00069.html", "name": "FEDORA-2009-8177", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "The Admin media handler in core/servers/basehttp.py in Django 1.0 and 0.96 does not properly map URL requests to expected \"static media files,\" which allows remote attackers to conduct directory traversal attacks and read arbitrary files via a crafted URL."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:django_project:django:1.0:*:*:*:*:*:*:*", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:django_project:django:0.96:*:*:*:*:*:*:*", "cpe_name": []}]}]}, "impact": {"baseMetricV2": {"cvssV2": {"version": "2.0", "vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N", "accessVector": "NETWORK", "accessComplexity": "LOW", "authentication": "NONE", "confidentialityImpact": "PARTIAL", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 5.0}, "severity": "MEDIUM", "exploitabilityScore": 10.0, "impactScore": 2.9, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}}, "publishedDate": "2009-08-04T16:30Z", "lastModifiedDate": "2024-11-21T01:05Z"}