{"publishedDate": "2025-06-11T18:15Z", "lastModifiedDate": "2025-06-17T20:33Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2025-25032", "ASSIGNER": "psirt@us.ibm.com"}, "description": {"description_data": [{"lang": "en", "value": "IBM Cognos Analytics 11.2.0, 11.2.1, 11.2.2, 11.2.3, 11.2.4, 12.0.0, 12.0.1, 12.0.2, 12.0.3, and 12.0.4 could allow an authenticated user to cause a denial of service by sending a specially crafted request that would exhaust memory resources."}, {"lang": "es", "value": "IBM Cognos Analytics 11.2.0, 11.2.1, 11.2.2, 11.2.3, 11.2.4, 12.0.0, 12.0.1, 12.0.2, 12.0.3 y 12.0.4 podr\u00edan permitir que un usuario autenticado provoque una denegaci\u00f3n de servicio al enviar una solicitud especialmente manipulada que agotar\u00eda los recursos de memoria."}]}, "references": {"reference_data": [{"url": "https://www.ibm.com/support/pages/node/7234674", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-770"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 3.9, "impactScore": 3.6, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "baseScore": 7.5, "baseSeverity": "HIGH", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:*:*:*:*:*:*:*:*", "matchCriteriaId": "792D3191-C65E-41C3-834D-45F162020756", "cpe_name": [], "versionStartIncluding": "11.2.0", "versionEndIncluding": "11.2.4"}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:*:*:*:*:*:*:*:*", "matchCriteriaId": "24F0D898-0723-4F31-94BA-FC176ECFB86C", "cpe_name": [], "versionStartIncluding": "12.0.0", "versionEndIncluding": "12.0.4"}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.2.4:fixpack1:*:*:*:*:*:*", "matchCriteriaId": "07DC144D-62FC-4808-A77A-642871C1F8FC", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.2.4:fixpack2:*:*:*:*:*:*", "matchCriteriaId": "2A61B920-B490-48A8-BF00-13B8854683FD", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.2.4:fixpack3:*:*:*:*:*:*", "matchCriteriaId": "1F65BC6D-9A9D-45B9-919B-2855586C4F1B", "cpe_name": []}]}]}}