{"publishedDate": "2025-03-12T16:15Z", "lastModifiedDate": "2025-07-19T02:15Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2025-25568", "ASSIGNER": "cve@mitre.org"}, "description": {"description_data": [{"lang": "en", "value": "SoftEtherVPN 5.02.5187 is vulnerable to Use after Free in the Command.c file via the CheckNetworkAcceptThread function. NOTE: the Supplier disputes this because the use-after-free is not in the VPN software, but is instead in a separate tool that has no untrusted input and runs under the user's own privileges (it is a stress-testing tool for a networking stack)."}, {"lang": "es", "value": "SoftEtherVPN 5.02.5187 es vulnerable a uso despu\u00e9s de la liberaci\u00f3n en el archivo Command.c a trav\u00e9s de la funci\u00f3n CheckNetworkAcceptThread."}]}, "references": {"reference_data": [{"url": "https://filecenter.softether-upload.com/d/250715_001_79538/CVE-2025-25568.pdf", "name": "", "refsource": "", "tags": []}, {"url": "https://lzydry.github.io/CVE-2025-25568/", "name": "", "refsource": "", "tags": ["Exploit"]}, {"url": "https://lzydry.github.io/CVE-2025-25568/", "name": "", "refsource": "", "tags": ["Exploit"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-416"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 3.9, "impactScore": 5.9, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "baseScore": 9.8, "baseSeverity": "CRITICAL", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:softether:vpn:5.02.5187:*:*:*:*:*:*:*", "matchCriteriaId": "47768969-B8C7-4834-BF99-2433BE4D1E6A", "cpe_name": []}]}]}}