{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2021-46945", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "NVD-CWE-noinfo"}]}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/1e9ea8f4637026b8e965128953f2da061ccae9c4", "name": "https://git.kernel.org/stable/c/1e9ea8f4637026b8e965128953f2da061ccae9c4", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/1e9ea8f4637026b8e965128953f2da061ccae9c4", "name": "https://git.kernel.org/stable/c/1e9ea8f4637026b8e965128953f2da061ccae9c4", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/64e1eebe2131183174f4fbb6b1491355f96c6cde", "name": "https://git.kernel.org/stable/c/64e1eebe2131183174f4fbb6b1491355f96c6cde", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/64e1eebe2131183174f4fbb6b1491355f96c6cde", "name": "https://git.kernel.org/stable/c/64e1eebe2131183174f4fbb6b1491355f96c6cde", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/ac2f7ca51b0929461ea49918f27c11b680f28995", "name": "https://git.kernel.org/stable/c/ac2f7ca51b0929461ea49918f27c11b680f28995", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/ac2f7ca51b0929461ea49918f27c11b680f28995", "name": "https://git.kernel.org/stable/c/ac2f7ca51b0929461ea49918f27c11b680f28995", "refsource": "", "tags": ["Patch"]}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\next4: always panic when errors=panic is specified\n\nBefore commit 014c9caa29d3 (\"ext4: make ext4_abort() use\n__ext4_error()\"), the following series of commands would trigger a\npanic:\n\n1. mount /dev/sda -o ro,errors=panic test\n2. mount /dev/sda -o remount,abort test\n\nAfter commit 014c9caa29d3, remounting a file system using the test\nmount option \"abort\" will no longer trigger a panic.  This commit will\nrestore the behaviour immediately before commit 014c9caa29d3.\n(However, note that the Linux kernel's behavior has not been\nconsistent; some previous kernel versions, including 5.4 and 4.19\nsimilarly did not panic after using the mount option \"abort\".)\n\nThis also makes a change to long-standing behaviour; namely, the\nfollowing series commands will now cause a panic, when previously it\ndid not:\n\n1. mount /dev/sda -o ro,errors=panic test\n2. echo test > /sys/fs/ext4/sda/trigger_fs_error\n\nHowever, this makes ext4's behaviour much more consistent, so this is\na good thing."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*", "versionStartIncluding": "5.12.0", "versionEndExcluding": "5.12.3", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*", "versionStartIncluding": "5.11.0", "versionEndExcluding": "5.11.20", "cpe_name": []}]}]}, "impact": {"baseMetricV3": {"cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "attackVector": "LOCAL", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 5.5, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 1.8, "impactScore": 3.6}}, "publishedDate": "2024-02-27T19:04Z", "lastModifiedDate": "2024-11-21T06:34Z"}