{"publishedDate": "2025-02-14T17:15Z", "lastModifiedDate": "2025-03-14T10:15Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2024-3220", "ASSIGNER": "cna@python.org"}, "description": {"description_data": [{"lang": "en", "value": "There is a defect in the CPython standard library module \u201cmimetypes\u201d where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as \u201c/etc/mime.types\u201d) also being used on Windows, where they are user-writable locations (\u201cC:\\etc\\mime.types\u201d).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (\u201c[]\u201d) on Windows platforms to avoid using the default list of known file locations."}, {"lang": "es", "value": "Hay un defecto en el m\u00f3dulo de la librer\u00eda est\u00e1ndar CPython \u201cmimetypes\u201d donde en Windows la lista predeterminada de ubicaciones de archivos conocidas son editables, lo que significa que otros usuarios pueden crear archivos no v\u00e1lidos para provocar que se genere MemoryError al iniciar el entorno de ejecuci\u00f3n de Python o que las extensiones de archivo se interpreten como el tipo de archivo incorrecto. Este defecto es causado por las ubicaciones predeterminadas de las plataformas Linux y macOS (como \u201c/etc/mime.types\u201d) que tambi\u00e9n se usan en Windows, donde son ubicaciones editables por el usuario (\u201cC:\\etc\\mime.types\u201d). Para solucionar este problema, un usuario puede llamar a mimetypes.init() con una lista vac\u00eda (\u201c[]\u201d) en las plataformas Windows para evitar usar la lista predeterminada de ubicaciones de archivos conocidas."}]}, "references": {"reference_data": [{"url": "https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/", "name": "", "refsource": "", "tags": []}, {"url": "http://www.openwall.com/lists/oss-security/2025/02/14/8", "name": "", "refsource": "", "tags": []}, {"url": "https://security.netapp.com/advisory/ntap-20250314-0001/", "name": "", "refsource": "", "tags": []}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-426"}]}]}}, "impact": {"baseMetricV4": {"cvssV4": {"version": "4.0", "vectorString": "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X", "baseScore": 2.3, "baseSeverity": "LOW", "attackVector": "NETWORK", "attackComplexity": "LOW", "attackRequirements": "PRESENT", "privilegesRequired": "LOW", "userInteraction": "NONE", "vulnConfidentialityImpact": "NONE", "vulnIntegrityImpact": "LOW", "vulnAvailabilityImpact": "LOW", "subConfidentialityImpact": "NONE", "subIntegrityImpact": "NONE", "subAvailabilityImpact": "NONE", "exploitMaturity": "NOT_DEFINED", "confidentialityRequirement": "NOT_DEFINED", "integrityRequirement": "NOT_DEFINED", "availabilityRequirement": "NOT_DEFINED", "modifiedAttackVector": "NOT_DEFINED", "modifiedAttackComplexity": "NOT_DEFINED", "modifiedAttackRequirements": "NOT_DEFINED", "modifiedPrivilegesRequired": "NOT_DEFINED", "modifiedUserInteraction": "NOT_DEFINED", "modifiedVulnConfidentialityImpact": "NOT_DEFINED", "modifiedVulnIntegrityImpact": "NOT_DEFINED", "modifiedVulnAvailabilityImpact": "NOT_DEFINED", "modifiedSubConfidentialityImpact": "NOT_DEFINED", "modifiedSubIntegrityImpact": "NOT_DEFINED", "modifiedSubAvailabilityImpact": "NOT_DEFINED", "Safety": "NOT_DEFINED", "Automatable": "NOT_DEFINED", "Recovery": "NOT_DEFINED", "valueDensity": "NOT_DEFINED", "vulnerabilityResponseEffort": "NOT_DEFINED", "providerUrgency": "NOT_DEFINED"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}}