{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2024-32979", "ASSIGNER": "security-advisories@github.com"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://github.com/nautobot/nautobot/commit/42440ebd9b381534ad89d62420ebea00d703d64e", "name": "https://github.com/nautobot/nautobot/commit/42440ebd9b381534ad89d62420ebea00d703d64e", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/commit/42440ebd9b381534ad89d62420ebea00d703d64e", "name": "https://github.com/nautobot/nautobot/commit/42440ebd9b381534ad89d62420ebea00d703d64e", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/pull/5646", "name": "https://github.com/nautobot/nautobot/pull/5646", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/pull/5646", "name": "https://github.com/nautobot/nautobot/pull/5646", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/pull/5647", "name": "https://github.com/nautobot/nautobot/pull/5647", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/pull/5647", "name": "https://github.com/nautobot/nautobot/pull/5647", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/security/advisories/GHSA-jxgr-gcj5-cqqg", "name": "https://github.com/nautobot/nautobot/security/advisories/GHSA-jxgr-gcj5-cqqg", "refsource": "", "tags": []}, {"url": "https://github.com/nautobot/nautobot/security/advisories/GHSA-jxgr-gcj5-cqqg", "name": "https://github.com/nautobot/nautobot/security/advisories/GHSA-jxgr-gcj5-cqqg", "refsource": "", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "Nautobot is a Network Source of Truth and Network Automation Platform built as a web application atop the Django Python framework with a PostgreSQL or MySQL database. It was discovered that due to improper handling and escaping of user-provided query parameters, a maliciously crafted Nautobot URL could potentially be used to execute a Reflected Cross-Site Scripting (Reflected XSS) attack against users. All filterable object-list views in Nautobot are vulnerable. This issue has been fixed in Nautobot versions 1.6.20 and 2.2.3. There are no known workarounds for this vulnerability.\n"}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": []}, "impact": {}, "publishedDate": "2024-05-01T11:15Z", "lastModifiedDate": "2024-11-21T09:16Z"}