{"publishedDate": "2024-04-25T16:15Z", "lastModifiedDate": "2025-06-30T13:49Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2023-6787", "ASSIGNER": "secalert@redhat.com"}, "description": {"description_data": [{"lang": "en", "value": "A flaw was found in Keycloak that occurs from an error in the re-authentication mechanism within org.keycloak.authentication. This flaw allows hijacking an active Keycloak session by triggering a new authentication process with the query parameter \"prompt=login,\" prompting the user to re-enter their credentials. If the user cancels this re-authentication by selecting \"Restart login,\" an account takeover may occur, as the new session, with a different SUB, will possess the same SID as the previous session."}, {"lang": "es", "value": "Se encontr\u00f3 una falla en Keycloak que se produce por un error en el mecanismo de reautenticaci\u00f3n dentro de org.keycloak.authentication. Esta falla permite secuestrar una sesi\u00f3n activa de Keycloak al activar un nuevo proceso de autenticaci\u00f3n con el par\u00e1metro de consulta \"prompt=login\", solicitando al usuario que vuelva a ingresar sus credenciales. Si el usuario cancela esta reautenticaci\u00f3n seleccionando \"Reiniciar inicio de sesi\u00f3n\", puede ocurrir una apropiaci\u00f3n de la cuenta, ya que la nueva sesi\u00f3n, con un SUB diferente, poseer\u00e1 el mismo SID que la sesi\u00f3n anterior."}]}, "references": {"reference_data": [{"url": "https://access.redhat.com/errata/RHSA-2024:1867", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2024:1868", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/security/cve/CVE-2023-6787", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2254375", "name": "", "refsource": "", "tags": ["Issue Tracking", "Vendor Advisory"]}, {"url": "https://github.com/keycloak/keycloak/security/advisories/GHSA-c9h6-v78w-52wj", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2024:1867", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2024:1868", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/security/cve/CVE-2023-6787", "name": "", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2254375", "name": "", "refsource": "", "tags": ["Issue Tracking", "Vendor Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-287"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 2.8, "impactScore": 5.9, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H", "baseScore": 8.8, "baseSeverity": "HIGH", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "REQUIRED", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:redhat:build_of_keycloak:-:*:*:*:text-only:*:*:*", "matchCriteriaId": "1830E455-7E11-4264-862D-05971A42D4A6", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:redhat:keycloak:*:*:*:*:*:*:*:*", "matchCriteriaId": "4933958F-429C-4C29-A18E-82E96B095783", "cpe_name": [], "versionEndExcluding": "22.0.10"}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:redhat:keycloak:*:*:*:*:*:*:*:*", "matchCriteriaId": "6392BA3C-DA57-4640-BB46-C11E9EC3DAED", "cpe_name": [], "versionStartIncluding": "23.0.0", "versionEndExcluding": "24.0.3"}]}]}}