{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2023-47712", "ASSIGNER": "psirt@us.ibm.com"}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/271524", "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/271524", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/271524", "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/271524", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://www.ibm.com/support/pages/node/7150840", "name": "https://www.ibm.com/support/pages/node/7150840", "refsource": "", "tags": ["Vendor Advisory"]}, {"url": "https://www.ibm.com/support/pages/node/7150840", "name": "https://www.ibm.com/support/pages/node/7150840", "refsource": "", "tags": ["Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "IBM Security Guardium 11.3, 11.4, 11.5, and 12.0 could allow a local user to gain elevated privileges on the system due to improper permissions control.  IBM X-Force ID:  271527."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:security_guardium:11.3:*:*:*:*:*:*:*", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:security_guardium:11.4:*:*:*:*:*:*:*", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:security_guardium:11.5:*:*:*:*:*:*:*", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:a:ibm:security_guardium:12.0:*:*:*:*:*:*:*", "cpe_name": []}]}]}, "impact": {}, "publishedDate": "2024-05-14T13:56Z", "lastModifiedDate": "2025-01-14T21:06Z"}