{"cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2020-36786", "ASSIGNER": "cve@kernel.org"}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-401"}]}]}, "references": {"reference_data": [{"url": "https://git.kernel.org/stable/c/27d2eab69f7da8e94e4751ac5c6d22d809275484", "name": "https://git.kernel.org/stable/c/27d2eab69f7da8e94e4751ac5c6d22d809275484", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/27d2eab69f7da8e94e4751ac5c6d22d809275484", "name": "https://git.kernel.org/stable/c/27d2eab69f7da8e94e4751ac5c6d22d809275484", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/4f0f37d03cde8f4341df8454f9b40a67fda94a33", "name": "https://git.kernel.org/stable/c/4f0f37d03cde8f4341df8454f9b40a67fda94a33", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/4f0f37d03cde8f4341df8454f9b40a67fda94a33", "name": "https://git.kernel.org/stable/c/4f0f37d03cde8f4341df8454f9b40a67fda94a33", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/6045b01dd0e3cd3759eafe7f290ed04c957500b1", "name": "https://git.kernel.org/stable/c/6045b01dd0e3cd3759eafe7f290ed04c957500b1", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/6045b01dd0e3cd3759eafe7f290ed04c957500b1", "name": "https://git.kernel.org/stable/c/6045b01dd0e3cd3759eafe7f290ed04c957500b1", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/cc4cc2fb5aaf9adb83c02211eb13b16cfcb7ba64", "name": "https://git.kernel.org/stable/c/cc4cc2fb5aaf9adb83c02211eb13b16cfcb7ba64", "refsource": "", "tags": ["Patch"]}, {"url": "https://git.kernel.org/stable/c/cc4cc2fb5aaf9adb83c02211eb13b16cfcb7ba64", "name": "https://git.kernel.org/stable/c/cc4cc2fb5aaf9adb83c02211eb13b16cfcb7ba64", "refsource": "", "tags": ["Patch"]}]}, "description": {"description_data": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nmedia: [next] staging: media: atomisp: fix memory leak of object flash\n\nIn the case where the call to lm3554_platform_data_func returns an\nerror there is a memory leak on the error return path of object\nflash.  Fix this by adding an error return path that will free\nflash and rename labels fail2 to fail3 and fail1 to fail2."}]}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*", "versionStartIncluding": "5.11", "versionEndExcluding": "5.11.21", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*", "versionStartIncluding": "5.12", "versionEndExcluding": "5.12.4", "cpe_name": []}, {"vulnerable": true, "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*", "versionStartIncluding": "5.10", "versionEndExcluding": "5.10.37", "cpe_name": []}]}]}, "impact": {"baseMetricV3": {"cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "attackVector": "LOCAL", "attackComplexity": "LOW", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH", "baseScore": 5.5, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 1.8, "impactScore": 3.6}}, "publishedDate": "2024-02-28T09:15Z", "lastModifiedDate": "2024-12-06T15:59Z"}