{"publishedDate": "2022-11-14T07:15Z", "lastModifiedDate": "2024-11-21T07:28Z", "cve": {"data_type": "CVE", "data_format": "MITRE", "data_version": "1.0", "CVE_data_meta": {"ID": "CVE-2022-45199", "ASSIGNER": "cve@mitre.org"}, "description": {"description_data": [{"lang": "en", "value": "Pillow before 9.3.0 allows denial of service via SAMPLESPERPIXEL."}, {"lang": "es", "value": "Pillow anterior a 9.3.0 permite la denegaci\u00f3n de servicio a trav\u00e9s de SAMPLESPERPIXEL."}]}, "references": {"reference_data": [{"url": "https://bugs.gentoo.org/878769", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "name": "", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/pull/6700", "name": "", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "name": "", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}, {"url": "https://security.gentoo.org/glsa/202211-10", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}, {"url": "https://bugs.gentoo.org/878769", "name": "", "refsource": "", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/commit/2444cddab2f83f28687c7c20871574acbb6dbcf3", "name": "", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/pull/6700", "name": "", "refsource": "", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/python-pillow/Pillow/releases/tag/9.3.0", "name": "", "refsource": "", "tags": ["Release Notes", "Third Party Advisory"]}, {"url": "https://security.gentoo.org/glsa/202211-10", "name": "", "refsource": "", "tags": ["Third Party Advisory"]}]}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-400"}]}]}}, "impact": {"baseMetricV3": {"exploitabilityScore": 3.9, "impactScore": 3.6, "cvssV3": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "baseScore": 7.5, "baseSeverity": "HIGH", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "NONE", "integrityImpact": "NONE", "availabilityImpact": "HIGH"}}}, "configurations": {"CVE_data_version": "4.0", "nodes": [{"operator": "OR", "negate": false, "children": [], "cpe_match": [{"vulnerable": true, "cpe23Uri": "cpe:2.3:a:python:pillow:*:*:*:*:*:*:*:*", "matchCriteriaId": "20159090-CD99-4147-BDE5-3A374CB863FD", "cpe_name": [], "versionEndExcluding": "9.3.0"}]}]}}